---
- name: Wireguard role
  tags: [wireguard]
  block:

  # install
  - name: Install wireguard packages
    become: true
    ansible.builtin.apt:
      name: 
      - wireguard
      - openresolv
      state: present
      
  # network manager
  - ansible.builtin.import_tasks: network_manager.yml
  
  # DNS
  - name: DNS für VPN
    become: true
    ansible.builtin.copy:
      src: rc-manager.conf
      dest: /etc/NetworkManager/conf.d/rc-manager.conf
      force: true # the remote file will be replaced when contents are different than the source
      owner: root
      group: root
      mode: u=rw,g=r,o=r